project:
  type: website
  output-dir: docs

website:
  title: "Sofia Rodas"
  # favicon: images/favicon.png
  navbar:
     title: false
     logo: images/simple_logo.png
     logo-alt: "Sofia Rodas with swiggly lines around it"
     right:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - href: resources.qmd
        text: Resources
      - icon: square-github
        href: https://github.com/sofiiir
  page-footer: 
     left: Copyright 2025, Sofia Rodas
     right: 
      - icon: squares-github
        href: https://github.com/sofiiir

format:
  html:
    theme: styles.scss
      - journal
      - brand
    toc: true
    page-layout: full
    mainfont: Dosis



