---
title: "About"
---

## Professional aspirations

I enjoy synthesizing policy, science, data, and socio-economic data into actionable reports. I am also passionate about conservation especially in marine ecosystems. 

I completed my undergraduate education in environmental studies from Vassar College where I focused in marine conservation, biology, and anthropology. Receiving an interdisciplinary degree makes me passionate about finding multi-faceted solutions to complex sustainability and conservation issues. Adding data analysis skills to my portfolio will allow me to better address complex environmental issues. I am excited to apply my new found data skills to my passion of environmental investigations. 
 
## Hobbies 

I love being outside! My favorite activities are swimming leisurely in the ocean, jogging to the beach, hiking, and kayaking. I also love art. I enjoy ceramics, print making, and collaging. I love combining all of my passions through travel where I explore the outdoors, art, and culture in new environments. 